### ISSUE TITLE
Can't add content on mobile

### ISSUE THREAD

**Issue by edent** [voc/infobeamer-cms#12]
I couldn't find any way to upload content from my phone. No menu anywhere. Eventually switched to desktop mode.

![Screenshot_20240531-101443](https://github.com/voc/infobeamer-cms/assets/837136/b3438448-109c-487c-b088-2a459b31abc9)

**Comment by wlcx** [comment]
Thanks @edent , didn't see this until now since emf ran of a fork of this, but I've PRed a fix to this repo (the upstream!)
